
ERROR - [2018-02-15 12:49:26] (exception 4522 123145364045824) Internal Server Error: /human/check/daily
Traceback (most recent call last):
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/channels/handler.py", line 243, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/IMnight/human/views.py", line 100, in dailyStatusCheck
    user = self.request.user
NameError: name 'self' is not defined
ERROR - [2018-02-15 12:50:13] (exception 4540 123145527250944) Internal Server Error: /human/check/daily
Traceback (most recent call last):
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/channels/handler.py", line 243, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
TypeError: dailyStatusCheck() missing 1 required positional argument: 'request'
