ERROR - [2018-01-24 09:23:51] (exception 82207 123145470926848) Internal Server Error: /earth/use/vocher/
Traceback (most recent call last):
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/channels/handler.py", line 243, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/IMnight/earth/views.py", line 22, in hello_world
    return Response("Error occured when vocher used", status=HTTP_406_NOT_ACCEPTABLE)
NameError: name 'HTTP_406_NOT_ACCEPTABLE' is not defined
ERROR - [2018-01-24 12:05:33] (exception 82668 123145514647552) Internal Server Error: /earth/vocher/
Traceback (most recent call last):
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: earth_holdingvocher.be_used

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/channels/handler.py", line 243, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/serializers.py", line 738, in data
    ret = super(ListSerializer, self).data
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/rest_framework/serializers.py", line 656, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/db/models/query.py", line 272, in __iter__
    self._fetch_all()
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1063, in execute_sql
    cursor.execute(sql, params)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/YuChih/Project/IMnight2018_Backend/ENV/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: earth_holdingvocher.be_used
WARNING - [2018-01-26 13:17:15] (base 5326 123145464414208) Not Found: /jets
WARNING - [2018-01-26 13:17:18] (base 5326 123145464414208) Not Found: /jet
WARNING - [2018-01-26 13:17:20] (base 5326 123145459159040) Not Found: /jet/
WARNING - [2018-01-26 13:19:11] (base 5459 123145514328064) Not Found: /dashboard
WARNING - [2018-01-26 13:19:17] (base 5459 123145509072896) Not Found: /jet/dashboard/
WARNING - [2018-01-26 13:19:46] (base 5459 123145514328064) Not Found: /jet/dashboard/
